import Head from "next/head";
import { Container } from "@chakra-ui/layout";
import NavBar from "@/components/NavBar";
import Footer from "../Footer";

const Main = ({ children, title }) => {
  const t = `${title} - Anton Sokolchuk`;
  return (
    <>
      <Head>
        <title>{t}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Container maxW="container.lg">
        <NavBar />
        {children}
        <Footer />
      </Container>
    </>
  );
};

export default Main;
