import Head from "next/head";
import { Inter } from "next/font/google";
import { Flex } from "@chakra-ui/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex height="100vh" alignItems="center" justifyContent="center">
        <Flex direction="column" backgroundColor="gray.100">
          hello world
        </Flex>
      </Flex>
    </>
  );
}
