import Head from "next/head";
import { Container, Flex } from "@chakra-ui/layout";
import NavBar from "@/components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anton Sokolchuk - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Container maxW="container.md">
        <NavBar />
      </Container>
    </>
  );
}
